[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11.0"
