version: '3.8'

services:
  # Основное приложение
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://detoxbuddy:password@db:5432/detoxbuddy
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # База данных PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=detoxbuddy
      - POSTGRES_USER=detoxbuddy
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis для кэша и очередей
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Celery worker для фоновых задач
  celery:
    build: .
    environment:
      - DATABASE_URL=postgresql://detoxbuddy:password@db:5432/detoxbuddy
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: celery -A app.celery_app worker --loglevel=info

volumes:
  postgres_data:
  redis_data:
